# Generated by Django 4.0.5 on 2022-06-02 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('nome_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionamentoUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacionamentoUsuarios', models.ManyToManyField(to='rede_social.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Postagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=200, verbose_name='Conteudo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_social.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=200, verbose_name='Comentario')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_social.postagens', verbose_name='Postagens')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rede_social.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
