# Generated by Django 4.0.5 on 2022-06-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagens',
            name='data',
            field=models.DateTimeField(default=1, verbose_name='Data de publicação'),
            preserve_default=False,
        ),
    ]
