# Generated by Django 4.0.3 on 2022-06-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='amigos',
            field=models.ManyToManyField(blank=True, to='rede_social.pessoa'),
        ),
    ]
