# Generated by Django 4.0.5 on 2022-06-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0002_postagens_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagens',
            name='data',
            field=models.DateField(null=True, verbose_name='Data de publicação'),
        ),
    ]
